name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Build Success
      working-directory: ./build
      run: cmake .. && make
    - name: Perform CTest
      working-directory: ./build
      run: ctest
