name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Build Success
      run: |
        mkdir -p .github/logs
        cmake -B build -D CMAKE_BUILD_TYPE=Release 1> .github/logs/cmake.stdout.log 2> .github/logs/cmake.stderr.log
        cd build
        make -j 1> ../.github/logs/make.stdout.log 2> ../.github/logs/make.stderr.log
    - name: Perform CTest
      run: |
        cd build
        ctest -j -V
      # ctest -j $(nproc --all) -V
    - name: Upload Build Logs
      uses: actions/upload-artifact@v2
      with:
        name: build-logs
        path: |
          .github/logs
          ./build/CMakeFiles/CMakeOutput.log
          ./build/CMakeFiles/CMakeError.log
    - name: Upload Test Logs
      uses: actions/upload-artifact@v2
      with: 
        name: test-logs
        path: |
          ./build/Testing/Temporary/LastTest.log
          ./build/Testing/Temporary/CTestCostData.txt
